name: YouTube Channel Fetcher

on:
  schedule:
    - cron: "*/5 * * * *"  
  workflow_dispatch:

jobs:
  fetch-youtube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch YouTube HLS URLs
        env:
          YT_API_URL: ${{ secrets.YT_API_URL }}
        run: |
          cat > channels_input.json <<EOF
          [
            {"id":"TdwhCOFh9OA","Name":"Smoy Tv","logo":"https://s3.aynaott.com/storage/cbadf009eebf7506c7633b3a98a2f042","genre":"News","country":"BD","language":"Bangla"}
          ]
          EOF

          python3 - <<'PYTHON'
import json
import os
import requests

yt_api_url = os.environ.get("YT_API_URL")
channels = json.load(open("channels_input.json"))

output_json = []
m3u_lines = ["#EXTM3U"]

for ch in channels:
    video_id = ch["id"]
    # Construct API request
    url = f"{yt_api_url}{video_id}"

    try:
        resp = requests.get(url, timeout=15)
        resp.raise_for_status()
        data = resp.json()

        # Expecting HLS URL under "hlsManifestUrl"
        hls_url = data.get("hlsManifestUrl")
        if hls_url:
            m3u_lines.append(f'#EXTINF:-1 tvg-id="{video_id}" tvg-name="{ch["Name"]}" tvg-logo="{ch["logo"]}",{ch["Name"]}')
            m3u_lines.append(hls_url)

            # Append to output JSON
            ch_out = ch.copy()
            ch_out["hlsManifestUrl"] = hls_url
            output_json.append(ch_out)
    except Exception as e:
        print(f"Failed to fetch {video_id}: {e}")

# Write outputs
with open("yt_api.json", "w") as f:
    json.dump(output_json, f, indent=2)

with open("yt_playlist.m3u", "w") as f:
    f.write("\n".join(m3u_lines))
PYTHON

      - name: Upload outputs
        uses: actions/upload-artifact@v3
        with:
          name: yt-files
          path: |
            yt_api.json
            yt_playlist.m3u
