name: YouTube Channel Fetcher

on:
  schedule:
    - cron: "*/5 * * * *"  
  workflow_dispatch:

jobs:
  fetch-youtube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch script
        env:
          YT_API_URL: ${{ secrets.YT_API_URL }}
        run: python app.py

      - name: Upload outputs
        uses: actions/upload-artifact@v3
        with:
          name: yt-files
          path: |
            yt_api.json
            yt_playlist.m3u
